- id: librainian-update-staged
  name: LiBrainian staged index update
  description: Incrementally refresh LiBrainian index for staged files.
  entry: node scripts/hook-update-index.mjs
  language: system
  pass_filenames: true
  stages:
    - pre-commit
- id: generated-artifact-guard
  name: Generated artifact guard
  description: Fail when likely TypeScript emit artifacts appear in source-controlled paths.
  entry: node scripts/guard-generated-artifacts.mjs
  language: system
  pass_filenames: false
  stages:
    - pre-commit
