- id: librainian-update-staged
  name: LiBrainian staged index update
  description: Incrementally refresh LiBrainian index for staged files.
  entry: npx librainian update --staged
  language: system
  pass_filenames: false
  stages:
    - pre-commit
