name: "LiBrainian CI Index"
description: "Restore cached LiBrainian index, run incremental refresh, and optionally upload artifacts."

inputs:
  workspace-root:
    description: "Workspace directory to index."
    required: false
    default: "."
  cache-key:
    description: "Cache key for .librainian directory."
    required: true
  restore-keys:
    description: "Optional newline-delimited restore keys."
    required: false
    default: ""
  cache-path:
    description: "Path to cache (relative to workspace root)."
    required: false
    default: ".librainian"
  upload-artifact:
    description: "Upload index artifacts for cross-job sharing."
    required: false
    default: "false"
  artifact-name:
    description: "Artifact name when upload-artifact is true."
    required: false
    default: "librainian-index"

runs:
  using: "composite"
  steps:
    - name: Restore LiBrainian cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.workspace-root }}/${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.restore-keys }}

    - name: Refresh LiBrainian index
      shell: bash
      run: |
        set -euo pipefail
        workspace="${{ inputs.workspace-root }}"
        action_root="${{ github.action_path }}"
        repo_root="$(cd "${action_root}/../../.." && pwd)"
        tsx_bin="${repo_root}/node_modules/.bin/tsx"
        stall_timeout_seconds="${LIBRAINIAN_ACTION_STALL_TIMEOUT_SECONDS:-300}"
        hard_timeout_seconds="${LIBRAINIAN_ACTION_HARD_TIMEOUT_SECONDS:-900}"

        if ! [[ "${stall_timeout_seconds}" =~ ^[0-9]+$ ]] || [ "${stall_timeout_seconds}" -le 0 ]; then
          echo "[librainian-action] Invalid LIBRAINIAN_ACTION_STALL_TIMEOUT_SECONDS=${stall_timeout_seconds}; expected positive integer seconds."
          exit 1
        fi

        if ! [[ "${hard_timeout_seconds}" =~ ^[0-9]+$ ]] || [ "${hard_timeout_seconds}" -le 0 ]; then
          echo "[librainian-action] Invalid LIBRAINIAN_ACTION_HARD_TIMEOUT_SECONDS=${hard_timeout_seconds}; expected positive integer seconds."
          exit 1
        fi

        if [ "${hard_timeout_seconds}" -le "${stall_timeout_seconds}" ]; then
          echo "[librainian-action] LIBRAINIAN_ACTION_HARD_TIMEOUT_SECONDS must be greater than LIBRAINIAN_ACTION_STALL_TIMEOUT_SECONDS."
          exit 1
        fi

        cleanup_orphan_processes() {
          local pattern
          local pids
          pattern="src/cli/index.ts --workspace ${workspace}"
          pids="$(pgrep -f "${pattern}" || true)"
          if [ -z "${pids}" ]; then
            return
          fi
          echo "[librainian-action] Detected stale LiBrainian CLI processes: ${pids}"
          printf '%s\n' "${pids}" | xargs -r kill -TERM || true
          sleep 2
          printf '%s\n' "${pids}" | xargs -r kill -KILL || true
        }

        run_librainian_command() {
          local stage
          local log_file
          local status
          local cmd
          local cmd_pid
          local started_at
          local last_output_at
          local last_report_at
          local now
          local size
          local last_size
          local elapsed
          local idle
          local timeout_reason
          local bootstrap_idle
          local semantic_suffix
          stage="$1"
          shift
          cmd=( "${tsx_bin}" "${repo_root}/src/cli/index.ts" --workspace "${workspace}" "$@" )
          log_file="$(mktemp)"

          echo "[librainian-action] stage=${stage} stallTimeout=${stall_timeout_seconds}s hardTimeout=${hard_timeout_seconds}s command=${cmd[*]}"
          "${cmd[@]}" >"${log_file}" 2>&1 &
          cmd_pid=$!
          started_at=$(date +%s)
          last_output_at=${started_at}
          last_report_at=${started_at}
          last_size=0
          timeout_reason=""

          while kill -0 "${cmd_pid}" 2>/dev/null; do
            sleep 5
            now=$(date +%s)
            size=$(wc -c <"${log_file}" 2>/dev/null || echo 0)
            if [ "${size}" -gt "${last_size}" ]; then
              last_size="${size}"
              last_output_at="${now}"
            fi

            elapsed=$((now - started_at))
            idle=$((now - last_output_at))
            bootstrap_idle=""
            semantic_suffix=""

            if grep -q "\\[bootstrap-heartbeat\\]" "${log_file}" 2>/dev/null; then
              bootstrap_idle="$(grep -E "\\[bootstrap-heartbeat\\]" "${log_file}" | tail -n 1 | sed -E 's/.*idle=([0-9]+)s.*/\\1/' || true)"
              if [[ "${bootstrap_idle}" =~ ^[0-9]+$ ]]; then
                semantic_suffix=" bootstrapIdle=${bootstrap_idle}s"
                if [ "${bootstrap_idle}" -ge "${stall_timeout_seconds}" ]; then
                  timeout_reason="bootstrap_stall_timeout"
                  break
                fi
              fi
            fi

            if [ $((now - last_report_at)) -ge 30 ]; then
              echo "[librainian-action] stage=${stage} heartbeat elapsed=${elapsed}s idle=${idle}s logBytes=${size}${semantic_suffix}"
              last_report_at="${now}"
            fi

            if [ "${idle}" -ge "${stall_timeout_seconds}" ]; then
              timeout_reason="stall_timeout"
              break
            fi
            if [ "${elapsed}" -ge "${hard_timeout_seconds}" ]; then
              timeout_reason="hard_timeout"
              break
            fi
          done

          if [ -n "${timeout_reason}" ]; then
            echo "[librainian-action] stage=${stage} ${timeout_reason} elapsed=${elapsed}s idle=${idle}s."
            kill -TERM "${cmd_pid}" 2>/dev/null || true
            sleep 2
            kill -KILL "${cmd_pid}" 2>/dev/null || true
            echo "[librainian-action] stage=${stage} last output (tail):"
            tail -n 200 "${log_file}" || true
            cleanup_orphan_processes
            rm -f "${log_file}"
            return 124
          fi

          set +e
          wait "${cmd_pid}"
          status=$?
          set -e

          if [ "${status}" -eq 124 ]; then
            echo "[librainian-action] stage=${stage} timed out with exit=124."
            echo "[librainian-action] stage=${stage} last output (tail):"
            tail -n 200 "${log_file}" || true
            cleanup_orphan_processes
            rm -f "${log_file}"
            return 124
          fi

          if [ "${status}" -ne 0 ]; then
            echo "[librainian-action] stage=${stage} failed with exit=${status}."
            tail -n 200 "${log_file}" || true
            rm -f "${log_file}"
            return "${status}"
          fi

          if [ -s "${log_file}" ]; then
            cat "${log_file}"
          fi
          rm -f "${log_file}"
        }

        if [ ! -x "${tsx_bin}" ]; then
          echo "[librainian-action] Installing repository dependencies."
          npm ci --prefix "${repo_root}" --ignore-scripts
          npm rebuild --prefix "${repo_root}" better-sqlite3
        fi

        cleanup_orphan_processes

        did_bootstrap=0
        if [ ! -d "${workspace}/${{ inputs.cache-path }}" ]; then
          echo "[librainian-action] No existing index found, running bootstrap."
          run_librainian_command "bootstrap.initial" bootstrap --mode fast --no-claude-md --force-resume
          did_bootstrap=1
        fi

        if [ "${did_bootstrap}" -eq 1 ]; then
          echo "[librainian-action] Bootstrap completed; skipping incremental refresh."
        else
          set +e
          update_output="$(run_librainian_command "update.incremental" update --incremental 2>&1)"
          update_status=$?
          set -e

          if [ "${update_status}" -eq 0 ]; then
            if [ -n "${update_output}" ]; then
              printf '%s\n' "${update_output}"
            fi
          elif printf '%s' "${update_output}" | grep -q "No modified files found to index"; then
            echo "[librainian-action] Incremental refresh skipped (no modified files)."
          else
            if [ -n "${update_output}" ]; then
              printf '%s\n' "${update_output}"
            fi
            echo "[librainian-action] Incremental refresh failed, falling back to bootstrap."
            run_librainian_command "bootstrap.fallback" bootstrap --mode fast --no-claude-md --force
          fi
        fi

    - name: Save LiBrainian cache
      if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.workspace-root }}/${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

    - name: Upload LiBrainian artifacts
      if: inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        if-no-files-found: warn
        path: |
          ${{ inputs.workspace-root }}/${{ inputs.cache-path }}/librarian.sqlite
          ${{ inputs.workspace-root }}/${{ inputs.cache-path }}/state.json
