name: Bug Report
description: Report a reproducible bug in LiBrainian
title: "[BUG] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please include exact commands and output so we can reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug.
      placeholder: "LiBrainian query returns empty results after quickstart on a TypeScript repo."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What task is blocked and for whom?
      placeholder: "Our agent cannot retrieve auth-related context, blocking login feature work."
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How serious is this issue?
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which product area is affected?
      options:
        - cli
        - mcp
        - indexing
        - retrieval
        - bootstrap
        - docs
        - ci-release
        - evaluation
        - security
        - process
    validations:
      required: true
  - type: dropdown
    id: evidence_needed
    attributes:
      label: Evidence needed
      description: What evidence should be attached before implementation?
      options:
        - repro-required
        - traces-required
        - benchmark-required
    validations:
      required: true
  - type: dropdown
    id: user_impact
    attributes:
      label: User impact
      description: Primary user impact category.
      options:
        - blocker
        - degraded
        - minor
        - request
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Include minimal steps and exact commands from a clean shell.
      value: |
        1. ...
        2. ...
        3. ...
      placeholder: |
        npx librainian quickstart
        npx librainian query "Where is authentication enforced?"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Expected summary with related files and confidence score."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Received empty packs and confidence 0.0."
    validations:
      required: true
  - type: dropdown
    id: install_method
    attributes:
      label: Install method
      options:
        - npm install librainian
        - npx librainian
        - linked local package
        - other
    validations:
      required: true
  - type: input
    id: librainian_version
    attributes:
      label: LiBrainian version
      placeholder: "0.2.0"
    validations:
      required: true
  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: "20.20.0"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15.3 / Ubuntu 24.04"
    validations:
      required: true
  - type: dropdown
    id: repo_type
    attributes:
      label: Repository language mix
      options:
        - TypeScript / JavaScript
        - Python
        - Go
        - Rust
        - Mixed polyglot
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Repro evidence
      description: Paste relevant command output, stack traces, or screenshots that prove the issue.
      render: text
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define measurable completion conditions.
      placeholder: |
        - Running <command> no longer fails in the repro case.
        - A regression test is added for this failure mode.
        - No new warnings/errors in related CLI output.
    validations:
      required: true
  - type: textarea
    id: affected_files
    attributes:
      label: affected-files
      description: List concrete files expected to change. Use one path per line.
      placeholder: |
        src/cli/commands/query.ts
        src/api/query.ts
    validations:
      required: true
  - type: dropdown
    id: complexity_estimate
    attributes:
      label: complexity-estimate
      description: Agent complexity estimate for implementation.
      options:
        - S
        - M
        - L
    validations:
      required: true
  - type: input
    id: verification_command
    attributes:
      label: verification-command
      description: Exact command agents should run to verify the fix.
      placeholder: npm run build && npm test -- --run src/cli/commands/__tests__/query.test.ts
    validations:
      required: true
  - type: dropdown
    id: actionability
    attributes:
      label: Agent actionability label
      description: Choose which label triage should apply.
      options:
        - agent/actionable
        - agent/needs-human
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Closure Criteria (M0 issues)
        Before closing, paste this checklist in the closing comment:
        ```
        - [ ] Code merged to main: <PR link>
        - [ ] T0 passes: <CI link or npm test output>
        - [ ] T0.5 passes: <evidence>
        - [ ] Reality evidence: <type (a/b/c)> — <artifact or paste>
        ```
        See [REALITY_VERIFICATION.md](../../docs/LiBrainian/REALITY_VERIFICATION.md) for what counts as valid evidence.
